#ifndef __CONFIG_ZYNQMP_UZEG3_H
#define __CONFIG_ZYNQMP_UZEG3_H

#define CONFIG_ZYNQ_SDHCI0  0Xff160000
#define CONFIG_ZYNQ_SDHCI1	0xFF170000
#define CONFIG_ZYNQ_I2C0
#define CONFIG_ZYNQ_I2C1

#define CONFIG_SYS_I2C_ZYNQ

#define CONFIG_SATA_CEVA

#define CONFIG_ZYNQMP_XHCI_LIST {ZYNQMP_USB0_XHCI_BASEADDR}

#define CONFIG_NR_DRAM_BANKS	1

#include <configs/xilinx_zynqmp.h>

#endif /* __CONFIG_ZYNQMP_UZEG3_H */
